untyped

globalize_all_functions

void function PrinttDevFiles()
{
    printt( "|mp_rr_floppytown_dev.nut:                       file called.|" )
}


void function Floppytown_MapInit_Dev()
{
    if ( GetCurrentPlaylistVarBool( "ft_dev_enable", false ) ) // map editing, do not activate in normal use
    {
        EditorRefAreVisible()
        AreaBuildAreVisible()
        AddClientCommandCallback( "props",  ClientCommand_Props )
        AddClientCommandCallback( "god",    ClientCommand_Invulnerable )
        AddClientCommandCallback( "test",   ClientCommand_Test )
        AddClientCommandCallback( "cyl",    ClientCommand_DebugCylender )
        AddClientCommandCallback( "asset",  ClientCommand_AssetViewerActive )
        AddClientCommandCallback( "fall",   ClientCommand_FallingObjectActiveThread )
        AddClientCommandCallback( "ent",    ClientCommand_EntGenerator )
        AddClientCommandCallback( "hud",    ClientCommand_HUD_Test )
    }
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
/////   become useless since in dev mode we can see the number of entities on the map in real time   /////
//////////////////////////////////////////////////////////////////////////////////////////////////////////
    bool function ClientCommand_Props( entity player, array<string> args )
    {   PrinttPropsCount(); return true }

    int function PropsCount()
    {
        int count = 0
        foreach( EntitiesCount in GetPropsCount() )
        { count++ }
        return count
    }

    array< entity > function GetPropsCount()
    {
        array< entity > EntitiesCount = GetEntArrayByScriptName( "FloppytownEntities" )
        return EntitiesCount
    }

    void function PrinttPropsCount()
    {
        printt( "" )
        printt( "Models generated by Floppytown scripts: " + PropsCount() )
        printt( "" )
    }
//////////////////////////////////////////////////////////////////////////////////////////////////////////

bool function ClientCommand_Invulnerable( entity player, array<string> args )
{
    if ( player.IsInvulnerable() )
    {
        player.ClearInvulnerable()
        printt( player.GetPlayerName() + " is now vulnerable." )
    }
    else
    {
        player.SetInvulnerable()
        player.SetHealth( 100 )

        printt( player.GetPlayerName() + " is invulnerable !")
    }

return true }

bool function ClientCommand_Test( entity player, array<string> args )
{
    
return true }

bool function ClientCommand_DebugCylender( entity player, array<string> args )
{
    foreach( ent in GetEntArrayByClass_Expensive( "trigger_cylinder" ) )
    {
        DebugDrawCylinder( ent.GetOrigin(), ent.GetAngles() + < -90, 0, 0 >, ent.GetRadius(), ent.GetAboveHeight(), 55, 120, 194, false, 40.0 )
        DebugDrawCylinder( ent.GetOrigin(), ent.GetAngles() + < -90, 45, 0 >, ent.GetRadius(), ent.GetAboveHeight(), 55, 120, 194, false, 40.0 )
    }
return true }

bool function ClientCommand_HUD_Test( entity player, array<string> args )
{
    Remote_CallFunction_NonReplay( player, "ServerCallback_HUD_Test_DoAnnouncement" )
return true }

bool function ClientCommand_AssetViewerActive( entity player, array<string> args )
{
    int j = 1
    int k = 1
    int l = 0
    int props_count = 0
    int max_props_count = ASSET_VIEWER_ARRAY.len() + 4


    CreateFloppytownModel( DOMESTIC_YUKI_MEMORIAL_02, FT_BUILD_AREA_POS + < -2000, 3000, 5480 >, < 0, 0, 0 >, "assetViewer" ).SetModelScale( 500 )
    CreateFloppytownModel( DOMESTIC_YUKI_MEMORIAL_03, FT_BUILD_AREA_POS + < 4600, 9000, 5480 >, < 0, 90, 0 >, "assetViewer" ).SetModelScale( 500 )
    CreateFloppytownModel( DOMESTIC_YUKI_MEMORIAL_04, FT_BUILD_AREA_POS + < 16600, 9758, 5480 >, < 0, -90, 0 >, "assetViewer" ).SetModelScale( 500 )

    for ( int i = 0 ; i < ASSET_VIEWER_ARRAY.len() ; i++ )
    {

        entity assets = CreateFloppytownModel( ASSET_VIEWER_ARRAY[i], FT_BUILD_AREA_POS + < 0, 0, 1000 > + < 800 * l, 800 * j, 800 * k >, < 0, 0, 0 >, "assetViewer" )

        k++

        if ( k == 11 )
        {
            j = j+1
            k = k-10

            if ( j >= 10 )
            {
                l = l+1
                j = 10
            }
        } 
    }

    foreach ( props in GetEntArrayByScriptName( "assetViewer" ) )
    { props_count++ }

    
    if ( props_count >= max_props_count )
    {
        foreach ( props in GetEntArrayByScriptName( "assetViewer" ) )
        {
            props.Destroy()
        }
        printt( "" )
        printt("Asset Viewer Closed")
        printt( "" )
    }
    else
    {
        printt( "" )
        printt("Asset Viewer Opened")
        printt( "" )
    }

return true }

bool function ClientCommand_FallingObjectActiveThread( entity player, array<string> args )
{
    if ( !Flag( "FallingObjectThread()_IsActive" ) ) // prevents it from being activated 2 times
    {
        printt( "|==========================================================|" )
        printt( "| FallingObjectThread(): Thread activate by client command" )
        printt( "|" )
        printt( "| Player: " + player )

        entity player_trigger = GetEnt( "player_trigger_01" )

        if ( IsValid( player_trigger ) )
        {
            player_trigger.Destroy()
        }

        FlagSet( "FallingObjectThread()_IsActive" )

        thread ChangePanelState()
        thread FallingObjectThread()
    }
    else
    {
        printt( "|==========================================================|" )
        printt( "| FallingObjectThread(): Thread is already activate" )
        printt( "|==========================================================|" )
    }

return true }

bool function ClientCommand_EntGenerator( entity player, array<string> args )
{
    foreach( ent in FLOPPYTOWN_ENTITIES )
    {

    }
return true }
